import './global.css';
import ThemeProvider from '../providers/ThemeProvider';
import ReduxProvider from '../providers/ReduxProvider';
import Footer from '../components/Footer';

export const metadata = {
  title: 'Welcome to frontend',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="tr">
      <body>
        <ReduxProvider>
          <ThemeProvider>
            <div style={{ display: "flex", flexDirection: "column" }}>
              <div >
                {children}
              </div>
              <Footer />
            </div>
          </ThemeProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}
