import './global.css';
import ThemeProvider from '../components/ThemeProvider';

export const metadata = {
  title: 'Welcome to frontend',
  description: 'Generated by create-nx-workspace',
};



export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="tr">
      <body>
        <ThemeProvider>
          <div style={{ display: "flex", flexDirection: "column" }}>
            <div >
              {children}
            </div>
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
